# Generated by Django 4.2.7 on 2023-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_time_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
