# Generated by Django 4.2.7 on 2023-11-23 19:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="last_time_read",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="readingsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("number_of_reading_sessions", models.PositiveIntegerField(default=0)),
                (
                    "total_reading_time",
                    models.DurationField(default=datetime.timedelta),
                ),
                (
                    "last_book_read",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reader.book",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
