# Generated by Django 4.2.7 on 2023-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(default="Unknown author", max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year_of_publishing",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
