# Generated by Django 4.2.7 on 2023-11-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0005_profile_total_reading_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_book_read",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reader.book",
            ),
        ),
    ]
